### ISSUE TITLE
Request failed with status code 401

### ISSUE THREAD

**Issue by benbonn** [thannaske/oekofen-json-documentation#4]
Since today 11:30 I am getting "AxiosError: Request failed with status code 401". 
No change on adapter, no change on Ökofen

**Comment by thannaske** [comment]
I don't think that this belongs here. HTTP 401 indicates that there is an authentication error. However, this has nothing to do with the documentation of the API itself.

**Comment by benbonn** [comment]
true, apologies, this was a due to a conflict with my test instance. Adapter is working very well!
